services:
  postgres:
    image: postgres:14-alpine
    container_name: os-project-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    
  webapp:
    build:
      context: . 
    container_name: os-project-webapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      USER: myuser
      HOST: postgres
      DATABASE: postgres 
      PASSWORD: mypassword
      DB_PORT: 5432

volumes:
  db-data: