---
version: "3.8"
services:
  webapp:
    image: osprojectregistry.azurecr.io/os-project-webapp:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE
      - USER
      - PASSWORD
      - HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
